/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.79).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AvailabilityResponse;
import io.swagger.model.ErrorResponse;
import org.threeten.bp.LocalDate;
import io.swagger.model.Room;
import io.swagger.model.RoomPage;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2026-05-23T09:51:35.242507730Z[GMT]")
@Validated
public interface RoomsApi {

    @Operation(summary = "Check room availability", description = "Checks whether a specific room is available for the given date range. Both checkIn and checkOut dates are required. checkIn must be today or later, checkOut must be after checkIn. ", tags={ "Availability" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Availability result", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AvailabilityResponse.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid date range (e.g. checkOut before checkIn, dates in the past)", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "404", description = "Room not found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/rooms/{roomId}/availability",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AvailabilityResponse> checkRoomAvailability(@Parameter(in = ParameterIn.PATH, description = "Unique identifier of the hotel room", required=true, schema=@Schema()) @PathVariable("roomId") Long roomId
, @NotNull @Parameter(in = ParameterIn.QUERY, description = "Check-in date (inclusive)" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "checkIn", required = true) LocalDate checkIn
, @NotNull @Parameter(in = ParameterIn.QUERY, description = "Check-out date (exclusive)" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "checkOut", required = true) LocalDate checkOut
);


    @Operation(summary = "Get room details", description = "Returns full details of a specific hotel room including extras.", tags={ "Rooms" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Room details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Room.class))),
        
        @ApiResponse(responseCode = "404", description = "Room not found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/rooms/{roomId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Room> getRoomById(@Parameter(in = ParameterIn.PATH, description = "Unique identifier of the hotel room", required=true, schema=@Schema()) @PathVariable("roomId") Long roomId
);


    @Operation(summary = "List hotel rooms (paginated)", description = "Returns a paginated list of hotel rooms with their details and extras. Default page size is 5 rooms per page. ", tags={ "Rooms" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Paginated list of hotel rooms", content = @Content(mediaType = "application/json", schema = @Schema(implementation = RoomPage.class))) })
    @RequestMapping(value = "/rooms",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<RoomPage> getRooms(@Min(0)@Parameter(in = ParameterIn.QUERY, description = "Page number (0-indexed)" ,schema=@Schema(allowableValues={ "0" }
, defaultValue="0")) @Valid @RequestParam(value = "page", required = false, defaultValue="0") Integer page
, @Min(1) @Max(20) @Parameter(in = ParameterIn.QUERY, description = "Number of rooms per page" ,schema=@Schema(allowableValues={ "1", "20" }, minimum="1", maximum="20"
, defaultValue="5")) @Valid @RequestParam(value = "size", required = false, defaultValue="5") Integer size
);

}

